# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import vnpt_asr_pb2 as vnpt__asr__pb2
from . import vnpt_asr_pb2 as vnpt__asr__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vnpt_asr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VnptSpeechRecognitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/vnpt.audio.asr.VnptSpeechRecognition/Recognize',
                request_serializer=vnpt__asr__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=vnpt__asr__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.StreamingRecognize = channel.stream_stream(
                '/vnpt.audio.asr.VnptSpeechRecognition/StreamingRecognize',
                request_serializer=vnpt__asr__pb2.StreamingRecognizeRequest.SerializeToString,
                response_deserializer=vnpt__asr__pb2.StreamingRecognizeResponse.FromString,
                _registered_method=True)


class VnptSpeechRecognitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRecognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VnptSpeechRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=vnpt__asr__pb2.RecognizeRequest.FromString,
                    response_serializer=vnpt__asr__pb2.RecognizeResponse.SerializeToString,
            ),
            'StreamingRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingRecognize,
                    request_deserializer=vnpt__asr__pb2.StreamingRecognizeRequest.FromString,
                    response_serializer=vnpt__asr__pb2.StreamingRecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vnpt.audio.asr.VnptSpeechRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vnpt.audio.asr.VnptSpeechRecognition', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VnptSpeechRecognition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vnpt.audio.asr.VnptSpeechRecognition/Recognize',
            vnpt__asr__pb2.RecognizeRequest.SerializeToString,
            vnpt__asr__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamingRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vnpt.audio.asr.VnptSpeechRecognition/StreamingRecognize',
            vnpt__asr__pb2.StreamingRecognizeRequest.SerializeToString,
            vnpt__asr__pb2.StreamingRecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
